import Head from "next/head"
import Image from "next/image"
import { Button } from "~/components/ui/button"

type User = {
  name: string
  title: string
  email: string

  photoUrl: string
}

export default function Home() {
  const users: User[] = [
    { name: "John Doe", title: "CEO", email: "", photoUrl: "" },
    { name: "John Doe", title: "CEO", email: "", photoUrl: "" },
    { name: "John Doe", title: "CEO", email: "", photoUrl: "" }
  ]

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-full place-items-center">
        <Button>Helelelelelelelele</Button>
      </main>
    </>
  )
}
